In [1]:
import torch

In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
x. numel()  # numer of elements

12

In [4]:
x.shape

torch.Size([12])

In [5]:
x.reshape(3, 4)  # 4개씩 3묶음

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
torch.zeros((2, 3, 4))  # 4개씩 3묶음이 2묶음

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.randn(3, 4)  # N(0, 1)에서 랜덤 샘플링

tensor([[ 0.0552, -1.6658,  0.8006,  0.2769],
        [-0.0175,  0.4709,  1.3820, -0.6014],
        [-1.0188, -2.0799,  1.1440, -0.2235]])

In [9]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])  # shape: [3, 4]

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [10]:
X = torch.tensor([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])  # shape: [3, 4]
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
X[-1]

tensor([ 8,  9, 10, 11])

In [12]:
X[1:3]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
X[1, 2]

tensor(6)

In [14]:
X[1, 2] = 17
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5, 17,  7],
        [ 8,  9, 10, 11]])

In [15]:
X[:2, :] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

In [16]:
torch.exp(x)  # elementwise

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [17]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 3, 2, 2])

In [18]:
x + y  # elementwise

tensor([ 3,  5,  6, 10])

In [19]:
x - y  # elementwise

tensor([-1, -1,  2,  6])

In [20]:
x * y  # elementwise

tensor([ 2,  6,  8, 16])

In [21]:
x / y  # elementwise

tensor([0.5000, 0.6667, 2.0000, 4.0000])

In [22]:
x ** y  # elementwise

tensor([ 1,  8, 16, 64])

In [23]:
X = torch.arange(12).reshape(3, 4)                            # (3, 4)
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])  # (3, 4)

In [24]:
torch.cat([X, Y], dim=0)  # shape: (dim0, dim1, dim2, ...)
                          # dim0끼리 더하기 → (6, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])

In [25]:
torch.cat([X, Y], dim=1)

tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])

In [26]:
X == Y  # elementwise

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [27]:
X.sum()

tensor(66)

In [28]:
X.sum(axis=0)  # dim0를 없애기 → (3, 4) → (4,)

tensor([12, 15, 18, 21])

In [29]:
X.sum(axis=0, keepdims=True)  # dim0를 합치기 → (3, 4) → (1, 4)

tensor([[12, 15, 18, 21]])

In [30]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [31]:
a + b  # broadcasting → (3, 2)

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [32]:
before = id(Y)
Y = Y + X  # new Y 생성!!
id(Y) == before

False

In [33]:
before = id(X)
X += Y  # 이미 있던 X에 Y를 더함!!
id(X) == before

True

In [34]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [35]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)