In [1]:
import torch

In [2]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [3]:
A.T  # transpose

tensor([[0, 2, 4],
        [1, 3, 5]])

In [4]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()

In [5]:
A * B  # elementwise

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [6]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [7]:
A.sum(axis=0)  # (2, 3)에서 2개씩 더해서 axis 0을 reduce하면 (3, )

tensor([3., 5., 7.])

In [8]:
A.sum(axis=1)  # (2, 3)에서 3개씩 더해서 axis 1을 reduce하면 (2, )

tensor([ 3., 12.])

In [9]:
A.sum(axis=[0, 1]) == A.sum()

tensor(True)

In [10]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [11]:
sum_A = A.sum(axis=1, keepdims=True)  # (2, 3)에서 3개씩 더하되 축 살려서 (2, 1)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [12]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [13]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [14]:
x = torch.arange(3, dtype=torch.float32)
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [15]:
A.shape, x.shape

(torch.Size([2, 3]), torch.Size([3]))

In [16]:
torch.mv(A, x)  # matrix-vector multiplication → return vector

tensor([ 5., 14.])

In [17]:
A@x  # matrix-vector multiplication → return vector

tensor([ 5., 14.])

In [18]:
B = torch.ones(3, 4)

In [19]:
print(A, B)
torch.mm(A, B)  # matrix-matrix multiplication → return matrix

tensor([[0., 1., 2.],
        [3., 4., 5.]]) tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])

In [20]:
A@B  # matrix-matrix multiplication → return matrix

tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])