In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(
    nn.Linear(8, 128), CenteredLayer()
)

In [5]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-4.6566e-10, grad_fn=<MeanBackward0>)

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.rand(in_units, units))
        self.bias = nn.Parameter(torch.rand(units))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [7]:
linear = MyLinear(5, 3)

In [8]:
linear.weight

Parameter containing:
tensor([[0.1247, 0.4175, 0.1985],
        [0.4446, 0.6840, 0.2525],
        [0.7959, 0.0195, 0.7200],
        [0.6273, 0.8916, 0.3990],
        [0.1122, 0.6826, 0.3540]], requires_grad=True)

In [9]:
X = torch.rand(2, 5)
linear(X)

tensor([[1.6673, 2.5216, 2.1876],
        [1.3981, 1.9907, 1.9376]])

In [10]:
X = torch.rand(2, 64)
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(X)

tensor([[70.6785],
        [63.6630]])